[features]
resolution = true
skip-lint = false

[programs.devnet]
cryptrans = "B346Vx1KonmcvcHrXq6ukyNBKVTZKpmB79LESakd6ALB"

[programs.localnet]
cryptrans = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.mainnet]
cryptrans = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[toolchain]
anchor_version = "0.30.1"
